version: 1
services:
  - type: web
    name: tamil-handwriting-to-speech
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port 10000 --reload
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: UPLOAD_FOLDER
        value: "uploads"
    healthCheckPath: /docs  # Adjust this if necessary
